sonar.projectKey=waste-tracker-backend
sonar.projectName=Waste Tracker - Backend
sonar.sources=backend/app
sonar.tests=backend/tests
sonar.python.version=3.11
# Caminho onde o relatório de cobertura do pytest deve ser salvo
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.pytest_cache/**